default_chain: stride-testnet
chains:
  stride-testnet:
    key: eda
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26657     
    grpc-addr: http://0.0.0.0:9090    
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  gaia-testnet:
    key: eda
    chain-id: GAIA
    rpc-addr: http://178.62.45.187:23657       
    grpc-addr: http://178.62.45.187:23090   
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
EOF
